namespace InventoryPilot.Services;

public class UiText
{
    private static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>
    {
        ["Home"] = "Inicio",
        ["New inventory"] = "Nuevo inventario",
        ["My page"] = "Mi pagina",
        ["Search inventories, items, tags"] = "Buscar inventarios, elementos, etiquetas",
        ["Light"] = "Claro",
        ["Dark"] = "Oscuro",
        ["Register"] = "Registrarse",
        ["Login"] = "Iniciar sesion",
        ["Logout"] = "Cerrar sesion",
        ["Account"] = "Cuenta",
        ["Admin"] = "Admin",
        ["Inventory management"] = "Gestion de inventario",
        ["Build flexible inventories with custom IDs and custom fields."] = "Crea inventarios flexibles con IDs y campos personalizados.",
        ["Owners define templates. Teams fill items in table-first views, discuss changes, and keep data searchable."] = "Los propietarios definen plantillas. Los equipos completan elementos en tablas, conversan cambios y mantienen los datos buscables.",
        ["Latest inventories"] = "Inventarios recientes",
        ["Create inventory"] = "Crear inventario",
        ["Top 5 inventories"] = "Top 5 inventarios",
        ["Tag cloud"] = "Nube de etiquetas",
        ["Inventory"] = "Inventario",
        ["Inventories"] = "Inventarios",
        ["Items"] = "Elementos",
        ["Item"] = "Elemento",
        ["Owner"] = "Propietario",
        ["Category"] = "Categoria",
        ["Name"] = "Nombre",
        ["Search results for"] = "Resultados de busqueda para",
        ["Owned inventories"] = "Inventarios propios",
        ["Writable inventories"] = "Inventarios con acceso de escritura",
        ["Create new"] = "Crear nuevo",
        ["Delete selected"] = "Eliminar seleccionados",
        ["Filter"] = "Filtrar",
        ["Sort by name"] = "Ordenar por nombre",
        ["Sort by email"] = "Ordenar por email",
        ["User management"] = "Gestion de usuarios",
        ["Block selected"] = "Bloquear seleccionados",
        ["Unblock selected"] = "Desbloquear seleccionados",
        ["Delete users"] = "Eliminar usuarios",
        ["Make admin"] = "Hacer admin",
        ["Remove admin"] = "Quitar admin",
        ["Status"] = "Estado",
        ["Actions"] = "Acciones",
        ["Active"] = "Activo",
        ["Blocked"] = "Bloqueado",
        ["Yes"] = "Si",
        ["No"] = "No",
        ["Custom ID"] = "ID personalizado",
        ["Chat"] = "Chat",
        ["Settings"] = "Ajustes",
        ["Fields"] = "Campos",
        ["Access"] = "Acceso",
        ["Stats"] = "Estadisticas",
        ["Export"] = "Exportar",
        ["Add item"] = "Agregar elemento",
        ["Created"] = "Creado",
        ["Likes"] = "Me gusta",
        ["General settings"] = "Ajustes generales",
        ["Title"] = "Titulo",
        ["Description"] = "Descripcion",
        ["Image URL"] = "URL de imagen",
        ["Tags"] = "Etiquetas",
        ["Save now"] = "Guardar ahora",
        ["Save format"] = "Guardar formato",
        ["Save fields"] = "Guardar campos",
        ["Save access list"] = "Guardar accesos",
        ["New post"] = "Nueva publicacion",
        ["Post message"] = "Publicar mensaje",
        ["Markdown supported."] = "Markdown compatible.",
        ["Public write access for all authenticated users"] = "Escritura publica para usuarios autenticados",
        ["InventoryPilot keeps the table view front and center."] = "InventoryPilot mantiene las tablas como vista principal."
        ,
        ["Version"] = "Version",
        ["Autosave is idle"] = "Autoguardado inactivo",
        ["Cloud-hosted illustration URL"] = "URL de ilustracion alojada en la nube",
        ["Upload sends the image directly to Cloudinary and stores only the returned URL."] = "La carga envia la imagen directamente a Cloudinary y guarda solo la URL devuelta.",
        ["equipment, laptop, office"] = "equipos, portatil, oficina",
        ["Open dedicated editor"] = "Abrir editor dedicado",
        ["Public write"] = "Escritura publica",
        ["Preview"] = "Vista previa",
        ["Use drag and drop to reorder ID parts. Format tips are available from the help markers."] = "Usa arrastrar y soltar para reordenar partes del ID. Los consejos de formato estan en los iconos de ayuda.",
        ["Drag to reorder"] = "Arrastrar para reordenar",
        ["Drag"] = "Arrastrar",
        ["Fixed text"] = "Texto fijo",
        ["Format, e.g. D4 or yyyy"] = "Formato, p. ej. D4 o yyyy",
        ["Examples: D4 for zero-padded sequence, yyyy for year, X5 for hex."] = "Ejemplos: D4 para secuencia con ceros, yyyy para ano, X5 para hexadecimal.",
        ["Remove"] = "Quitar",
        ["Drop an element here to remove it."] = "Suelta un elemento aqui para quitarlo.",
        ["Add element"] = "Agregar elemento",
        ["Fixed fields like created_by, created_at, and custom_id are always included on the item form."] = "Los campos fijos como created_by, created_at y custom_id siempre se incluyen en el formulario del elemento.",
        ["Field title"] = "Titulo del campo",
        ["Description or tooltip text"] = "Descripcion o texto de ayuda",
        ["Select options: [\"Desktop\",\"Laptop\"]"] = "Opciones de seleccion: [\"Escritorio\",\"Portatil\"]",
        ["Regex pattern"] = "Patron regex",
        ["Max length"] = "Longitud maxima",
        ["Min value"] = "Valor minimo",
        ["Max value"] = "Valor maximo",
        ["Required"] = "Obligatorio",
        ["Show in table"] = "Mostrar en tabla",
        ["Drop a field here to remove it."] = "Suelta un campo aqui para quitarlo.",
        ["Add field"] = "Agregar campo",
        ["Write access"] = "Acceso de escritura",
        ["Autocomplete supports username and email."] = "El autocompletado admite nombre de usuario y email.",
        ["Users with write access"] = "Usuarios con acceso de escritura",
        ["Type a username or email"] = "Escribe un usuario o email",
        ["Avg"] = "Prom.",
        ["Range"] = "Rango",
        ["No values yet"] = "Sin valores aun",
        ["Export inventory"] = "Exportar inventario",
        ["CSV export includes fixed fields and all custom fields in display order."] = "La exportacion CSV incluye campos fijos y todos los campos personalizados en orden.",
        ["Download CSV"] = "Descargar CSV",
        ["Item details"] = "Detalles del elemento",
        ["New item"] = "Nuevo elemento",
        ["Edit mode"] = "Modo edicion",
        ["Read-only"] = "Solo lectura",
        ["Like"] = "Me gusta",
        ["Created by"] = "Creado por",
        ["Created at"] = "Creado el",
        ["Updated at"] = "Actualizado el",
        ["Will be set on save"] = "Se definira al guardar",
        ["Not saved yet"] = "Aun no guardado",
        ["True / false"] = "Verdadero / falso",
        ["Select"] = "Seleccionar",
        ["Open document"] = "Abrir documento",
        ["Save item"] = "Guardar elemento"
    };

    public string Get(HttpContext context, string key)
    {
        var language = context.Request.Cookies["language"];
        return string.Equals(language, "es", StringComparison.OrdinalIgnoreCase) && Spanish.TryGetValue(key, out var value)
            ? value
            : key;
    }
}
